# Generated by Django 5.2.13 on 2026-04-29 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
                ('client_name', models.TextField(blank=True, null=True)),
                ('status', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'project',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('task_description', models.TextField(blank=True, null=True)),
                ('assigned_to', models.TextField(blank=True, null=True)),
                ('priority', models.TextField(blank=True, null=True)),
                ('is_completed', models.BooleanField(blank=True, null=True)),
                ('project', models.ForeignKey(blank=True, db_column='project-id', null=True, on_delete=django.db.models.deletion.CASCADE, to='tracker.project')),
            ],
            options={
                'db_table': 'tasks',
                'db_table_comment': 'My dynamic project tasks',
                'managed': True,
            },
        ),
    ]
